apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: analytics-handler-3344
  namespace: MendPerformance
  annotations:
    github.com/project-slug: MendPerformance/analytics-handler-3344
spec:
  type: service
  lifecycle: unknown
  owner: mend.io
